//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point01Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfEvaluations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PointOfEvaluations()
        {
            this.DataForEvaluations = new HashSet<DataForEvaluations>();
            this.Scores = new HashSet<Scores>();
        }
    
        public int Id { get; set; }
        public System.DateTime Year { get; set; }
        public int Point { get; set; }
        public int SubPoint { get; set; }
        public string Name { get; set; }
        public decimal Weight { get; set; }
        public decimal Rate1 { get; set; }
        public decimal Rate2 { get; set; }
        public decimal Rate3 { get; set; }
        public decimal Rate4 { get; set; }
        public decimal Rate5 { get; set; }
        public Nullable<int> OwnerOfficeId { get; set; }
        public Nullable<int> AuditOfficeId { get; set; }
        public string UpdateUserId { get; set; }
        public int Plan { get; set; }
        public Nullable<int> Unit { get; set; }
        public string DetailPlan { get; set; }
        public string DetailRate1 { get; set; }
        public string DetailRate2 { get; set; }
        public string DetailRate3 { get; set; }
        public string DetailRate4 { get; set; }
        public string DetailRate5 { get; set; }
        public string Detail2Rate1 { get; set; }
        public string Detail2Rate2 { get; set; }
        public string Detail2Rate3 { get; set; }
        public string Detail2Rate4 { get; set; }
        public string Detail2Rate5 { get; set; }
        public Nullable<System.DateTime> Rate1MonthStart { get; set; }
        public Nullable<System.DateTime> Rate1MonthStart2 { get; set; }
        public Nullable<System.DateTime> Rate1MonthStop { get; set; }
        public Nullable<System.DateTime> Rate1MonthStop2 { get; set; }
        public Nullable<System.DateTime> Rate2MonthStart { get; set; }
        public Nullable<System.DateTime> Rate2MonthStart2 { get; set; }
        public Nullable<System.DateTime> Rate2MonthStop { get; set; }
        public Nullable<System.DateTime> Rate2MonthStop2 { get; set; }
        public Nullable<System.DateTime> Rate3MonthStart { get; set; }
        public Nullable<System.DateTime> Rate3MonthStart2 { get; set; }
        public Nullable<System.DateTime> Rate3MonthStop { get; set; }
        public Nullable<System.DateTime> Rate3MonthStop2 { get; set; }
        public Nullable<System.DateTime> Rate4MonthStart { get; set; }
        public Nullable<System.DateTime> Rate4MonthStart2 { get; set; }
        public Nullable<System.DateTime> Rate4MonthStop { get; set; }
        public Nullable<System.DateTime> Rate4MonthStop2 { get; set; }
        public Nullable<System.DateTime> Rate5MonthStart { get; set; }
        public Nullable<System.DateTime> Rate5MonthStart2 { get; set; }
        public Nullable<System.DateTime> Rate5MonthStop { get; set; }
        public Nullable<System.DateTime> Rate5MonthStop2 { get; set; }
        public string Ddrive { get; set; }
        public string ExpectPlan { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataForEvaluations> DataForEvaluations { get; set; }
        public virtual Offices Offices { get; set; }
        public virtual Offices Offices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scores> Scores { get; set; }
    }
}
